#!/bin/bash
#$ -N chunk_chr2
#$ -cwd
#$ -V
#$ -l h_rt=02:00:00
#$ -l h_vmem=4G
#$ -pe smp 1
#$ -o logs/chunk_chr2_$JOB_ID.out
#$ -e logs/chunk_chr2_$JOB_ID.err

set -euo pipefail

# Activate environment
module load miniforge
conda activate glimpse2

SITES_VCF="vcf/chr2.referencePanel.sites.vcf.gz"   
GENETIC_MAP="maps/chr2.gmap.gz"                         # genetic map for chr2
OUTFILE="chunks.chr2.txt"                                      # output chunks file

# Create logs dir if missing
mkdir -p logs

# Sanity checks
[[ -f "$SITES_VCF" ]] || { echo "Missing SITES_VCF: $SITES_VCF"; exit 1; }
[[ -f "$GENETIC_MAP" ]] || { echo "Missing GENETIC_MAP: $GENETIC_MAP"; exit 1; }

echo "[INFO] Running GLIMPSE2_chunk on chr2"
echo "[INFO] Sites: $SITES_VCF"
echo "[INFO] Map:   $GENETIC_MAP"
echo "[INFO] Out:   $OUTFILE"


GLIMPSE2_chunk \
  --input  "$SITES_VCF" \
  --region chr2 \
  --map    "$GENETIC_MAP" \
  --output "$OUTFILE"

echo "[DONE] Wrote chunk definitions to $OUTFILE"

conda deactivate
